USE ROLE MODEANALYTICS_R2;
USE WAREHOUSE MODEANALYTICS_VW_XSmall;

SELECT R_NAME as Region, N_NAME as Nation, COUNT(distinct O_ORDERKEY) as Orders
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.REGION
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.NATION
ON REGION.R_REGIONKEY = NATION.N_REGIONKEY
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER
ON CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.ORDERS
ON ORDERS.O_CUSTKEY = CUSTOMER.C_CUSTKEY
GROUP BY R_NAME, N_NAME;