USE ROLE MODEANALYTICS_R1;
USE WAREHOUSE MODEANALYTICS_VW_XSmall;

SELECT *
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION n
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER c 
ON n.N_NATIONKEY = c.C_NATIONKEY 
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS o 
ON c.C_CUSTKEY = o.O_CUSTKEY 
