SELECT c.CUSTOMER_ID, o.STATUS, COUNT(*)
FROM ANALYTICS.ANALYTICS_DEBUG.DIM_CUSTOMERS c 
  JOIN ANALYTICS.ANALYTICS_DEBUG.FCT_ORDERS o ON c.CUSTOMER_ID = o.CUSTOMER_ID 
GROUP BY c.CUSTOMER_ID, o.STATUS