-- Returns first 100 rows from tutorial.dunder_mifflin_paper_sales
  SELECT 
		order_id,
		purchased_at,
		status,
		cancelled_at,
		returned_at,
		product_id,
		product_name,
		price,
		discount,
		shipping_cost,
		quantity,
		business_size,
		payment_cycle,
		account_id,
		account_name,
		account_manager,
		days_to_close,
		shipping_mode,
		shipping_address,
		shipping_city,
		shipping_state,
		shipping_zip,
		shipping_region,
		shipping_latitude,
		shipping_longitude,
		days_to_ship,
		reviewed_at,
		rating,
		index,
		review
 FROM tutorial.dunder_mifflin_paper_sales
 WHERE account_manager = 'Dwight Schrute'