-- Returns first 100 rows from ANALYTICS.DBT_GGOHEEN.BASE__METRICS
SELECT * FROM ANALYTICS.DBT_GGOHEEN.BASE__METRICS LIMIT 100;

-- Returns first 100 rows from ANALYTICS.DBT_IRAO.MY_SECOND_DBT_MODEL
SELECT * FROM ANALYTICS.DBT_IRAO.MY_SECOND_DBT_MODEL LIMIT 100;