USE ROLE MODEANALYTICS_R1;
USE WAREHOUSE MODEANALYTICS_VW_XSmall;

SELECT R_NAME, N_NAME, C_NAME, C_ACCTBAL
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION n
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER c
ON n.N_NATIONKEY = c.C_NATIONKEY
INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION r 
ON n.N_REGIONKEY = r.R_REGIONKEY 