USE ROLE MODEANALYTICS_R1;

USE WAREHOUSE MODEANALYTICS_VW_XSmall;

SELECT
  N_NAME,
  C_MKTSEGMENT,
  C_NAME,
  C_ACCTBAL
FROM
  SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION
  INNER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER ON (
    NATION.N_NATIONKEY = CUSTOMER.C_NATIONKEY
  )