USE ROLE MODEANALYTICS_R1;

USE WAREHOUSE MODEANALYTICS_VW_XSmall;

SELECT
  C_MKTSEGMENT,
  C_NAME,
  year(O_ORDERDATE),
  MONTH(O_ORDERDATE),
  O_ORDERSTATUS,
  O_ORDERKEY,
  O_TOTALPRICE,
  O_COMMENT
FROM
  SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER
  LEFT OUTER JOIN SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS ON (CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY)